### ISSUE TITLE
DB Genres Table

### ISSUE THREAD

**Issue by bbiehl** [clburns107/02-29-pair-project#4]
- [ ] Action and Adventure
- [ ] Anime
- [ ] Children and Family
- [ ] Classics
- [ ] Comedies
- [ ] Cult Movies
- [ ] Documentaries
- [ ] Dramas
- [ ] Faith and Spirituality
- [ ] Gay and Lesbian
- [ ]  Horror
- [ ]  Independent
- [ ] International
- [ ]  Music
- [ ] Period Pieces
- [ ]  Romantic Movies
- [ ] Sci-Fi and Fantasy
- [ ] Sports and Fitness
- [ ] TV Shows
- [ ] Thrillers

**Comment by clburns107** [comment]
Leaving out genres for now. Searching by genre is a phase 3 or 4 feature
