### ISSUE TITLE
Images for posters via API not showing up in Production

### ISSUE THREAD

**Issue by sumeetjain** [clburns107/02-29-pair-project#49]
There seems to be an issue with the API that prevents images from being displayed on a real server (e.g. Heroku).

Not sure what the fix for this will be, but we'll figure something out. Beth/Derek will likely have the same challenge.

**Comment by bbiehl** [comment]
spoke with Beth and Derek re: this issue this morning.  Beth and Derek are having issues bringing up images when the images themselves do not exist on the OMDb database.
